Update kr.js
mty22/krunker.io-translations pull request #11
Opened 2021-03-29 15:43 UTC by YuniQ152

<3

2021-03-29 16:21 UTC, apinklover requested changes
Line 174: How about "KDR 표시"
Line 244: How about leaving out the parenthetical extra information?
Line 249: Pretty sure it's "게임 제목 숨기기"
Line 261: Change it to "게임패드 비활성화" for translation consistency
Line 339: Change "출발" to "시작" ?

2021-03-29 23:38 UTC, mty22 commented on kr.js
> +app.spectate.mobile 관전하려면 누르세요.
can you please remove the full stop (.) at the end on these lines please!

2021-03-29 23:38 UTC, mty22 commented on kr.js
> +app.spectate.controller 관전하려면 START를 누르세요.
same here, can you please remove the full stop (.) :)

2021-03-29 23:43 UTC, mty22 requested changes
Just need to change a few things. Have a look at @apinklover 's comment too please!

Also with your next commit(s), please add 'Resolves: #9' to the commit message. :)

2021-03-29 23:48 UTC, dojinshi commented
Changes looks awesome! Great work guys! :)

2021-03-30 08:15 UTC, mty22 approved these changes

2021-03-30 08:15 UTC, mty22 commented
@apinklover recheck please

2021-03-30 08:22 UTC, apinklover commented
Looks good. I approve

2021-03-30 08:31 UTC, merged

2021-03-30 08:31 UTC, mty22 commented
Cheers!