Update kr.js
mty22/krunker.io-translations pull request #130
Opened 2021-04-23 07:33 UTC by Baw-Appie

2021-04-23 07:55 UTC, mty22 commented
This is exactly the kind of work that I am looking for. Thanks for the updates, more so willing to be notified of `kr.js` changes/reviews via `CODEOWNERS`.

Just need a native speaker to review and we can merge it in.

2021-04-23 07:58 UTC, tr0922 commented
@mty22 @Baw-Appie I'll check on it

2021-04-23 08:17 UTC, tr0922 commented
@mty22 @Baw-Appie Done. Check the edits

382_지역 스탯
639_기본 설정 강제
744_그대로 가는 게 좋음 (애초에 "태그" 자체가 지정한다는 뜻임)
751_전반적 스탯
752_클래스 스탯
754_상점 판매 (수익)
756, 758, 760, 762_공개한-->발행한, 발표한
766_개가 전 세계에 있음
768, 770_제안-->제의
774_!는 빼기
775_이 거래에서 (나는) 아이템을 얻을 수 없습니다!

I'll keep on editing it, might want to edit by myself if this turns out bad :/
But I'm sure this is pog

2021-04-23 09:12 UTC, Baw-Appie commented
@tr0922 제안해주신대로 수정했으나, 744에서는 자연스러운 번역을 위해 변경하는게 맞을 것 같습니다.

2021-04-23 10:39 UTC, tr0922 commented
@Baw-Appie 👍

2021-04-24 08:27 UTC, mty22 requested changes
just need to remove some fullstops

otherwise, is this OK to merge? @tr0922

2021-04-24 08:27 UTC, mty22 commented on kr.js
> +item.sell.cant 이 아이템은 판매될 수 없습니다.
can you please remove the fullstops

2021-04-24 08:27 UTC, mty22 commented on kr.js
> +social.profile.skins.none 이 유저가 발행한 스킨이 없습니다.
remove fullstops here

2021-04-24 08:27 UTC, mty22 commented on kr.js
> +social.profile.games.none 이 유저가 발행한 게임이 없습니다.
remove fullstops here

2021-04-24 08:27 UTC, mty22 commented on kr.js
> +social.profile.assets.none 이 유저가 발행한 에셋이 없습니다.
remove fullstops here

2021-04-24 08:27 UTC, mty22 commented on kr.js
> +social.profile.mods.none 이 유저가 발행한 모드가 없습니다.
remove fullstops here

2021-04-24 08:33 UTC, Baw-Appie commented
I removed fullstops

2021-04-25 12:14 UTC, zVaderX requested changes
Review

2021-04-25 12:14 UTC, zVaderX commented on kr.js
> +server.config.fixMov 움직임 수정
수정된 움직임 
608

2021-04-25 12:14 UTC, zVaderX commented on kr.js
> +social.trades.accept 정말 이 거래를 수락할까요?
정말 이 거래를 수락하시겠습니까?
776

2021-04-25 12:24 UTC, tr0922 commented on kr.js
> +social.trades.accept 정말 이 거래를 수락할까요?
@Baw-Appie Maybe we should go with zVader's edit. It's way more formal and smooth.

2021-04-25 12:25 UTC, tr0922 commented
@mty22 Please wait a bit, might need some time to edit according to the reviews.

2021-04-26 06:50 UTC, YuniQ152 reviewed
Review

2021-04-26 06:50 UTC, YuniQ152 commented on kr.js
> +item.sell.cant 이 아이템은 판매될 수 없습니다
749: 이 아이템은 판매할 수 없습니다

2021-04-26 06:50 UTC, YuniQ152 commented on kr.js
> +social.trades.message 설정에서 거래 메시지를 활성화하세요
774: (메시지를 보려면) 설정에서 트레이드 메시지 표시를 활성화하세요

2021-04-26 06:50 UTC, YuniQ152 commented on kr.js
> +social.profile.mods.none 이 유저가 발행한 모드가 없습니다.
756-762: '발행한' -> '게시한'은 어떤가요

2021-04-26 06:51 UTC, YuniQ152 commented
'Trade'를 '거래'로 번역하신다면, 번역 일관성을 위해 기존에 '트레이드'로 번역되었던 166, 520, 692번째 줄에 대한 수정이 필요합니다.

2021-04-26 06:54 UTC, YuniQ152 commented on kr.js
> +social.trades.message 설정에서 거래 메시지를 활성화하세요
'Trade'를 '거래'로 번역하신다면:
메시지를 보려면 설정에서 거래 메시지 표시를 활성화하세요

2021-04-26 12:43 UTC, mty22 commented
@YuniQ152 please let me know once OK =)

2021-04-27 07:57 UTC, mty22 commented
![image](https://user-images.githubusercontent.com/2951231/116206389-154eb980-a782-11eb-939e-6c7852804f0d.png)

2021-04-27 08:00 UTC, mty22 approved these changes

2021-04-27 08:00 UTC, merged

2021-04-27 08:01 UTC, mty22 commented
KB role sorted, KR payment queued.