Updated jp.js(v3.8.2)
mty22/krunker.io-translations pull request #131
Opened 2021-04-23 08:43 UTC by Hiro527

- Fixed some sentences
- Updated for v3.8.2
- Replaced "！"(2Bytes char) to "!"(Byte char) for readability

2021-04-23 08:51 UTC, Hiro527 commented
I've already done all changes. Please check them.
@KnockerOut 時間あったら確認お願いします～

2021-04-24 08:13 UTC, mty22 commented on jp.js
> +windows.account.recover アカウントを復元するには、<a>krunker@yendis.ch</a>に連絡してください
この状況だっただら「回復」の方がいいかな？

辞書によると：
復元 - restore
回復 - recover

たとえば、このリンクを見てください：

https://support.microsoft.com/ja-jp/account-billing/%E5%BF%98%E3%82%8C%E3%81%A6%E3%81%97%E3%81%BE%E3%81%A3%E3%81%9F-microsoft-%E3%82%A2%E3%82%AB%E3%82%A6%E3%83%B3%E3%83%88%E3%81%AE%E3%83%91%E3%82%B9%E3%83%AF%E3%83%BC%E3%83%89%E3%82%92%E3%83%AA%E3%82%BB%E3%83%83%E3%83%88%E3%81%99%E3%82%8B-eff4f067-5042-c1a3-fe72-b04d60556c37

^^ 
![image](https://user-images.githubusercontent.com/2951231/115952341-b3474780-a528-11eb-9189-a838144fcef7.png)

どう思いますか？

2021-04-24 09:07 UTC, mty22 requested changes

2021-04-24 09:25 UTC, Hiro527 commented on jp.js
> +item.sell.cant このアイテムは販売できません。
あ、すいません。帰ったら修正します

2021-04-24 09:26 UTC, Hiro527 commented on jp.js
> +item.sell.quick 本当に{0}をクイックセルしますか?
確かに僕も統一したほうがいいと思います
ただ、「クイック販売」が不自然じゃないかどうかっていう疑問が少しあるんですよね

2021-04-24 09:27 UTC, Hiro527 commented on jp.js
> +windows.account.recover アカウントを復元するには、<a>krunker@yendis.ch</a>に連絡してください
本当ですね、回復のほうが多く使われているようなのでそちらに戻します👍
お手数おかけしてすいません

2021-04-24 11:27 UTC, Hiro527 commented
修正完了しました。確認お願いします。

2021-04-25 00:25 UTC, RIFLEJI commented on jp.js
> -social.trades.accept Are you sure you want to accept this offer?
Can I translate these few

2021-04-25 03:38 UTC, Hiro527 commented on jp.js
> -social.trades.accept Are you sure you want to accept this offer?
えっと、日本の方でしょうか？
もうすでに翻訳済みで現在再レビュー待ちになってます

2021-04-27 08:25 UTC, hassich approved these changes

2021-04-27 09:54 UTC, merged

2021-04-27 09:55 UTC, mty22 commented
@Hiro527さんと@hassichさんもありがとうございました！

2021-04-27 10:16 UTC, Hiro527 commented
Sorry for my mistakes
Thx for reviewing!

2021-04-28 04:22 UTC, mty22 commented on jp.js
> +item.sell.quick 本当に{0}をクイック販売しますか?
```[2:21 PM] NamekujiLSDs: 本当に{0}をクイックセールしますか？```

^ suggestion to fix this to make it sound more natural. I agree here.

2021-04-28 04:27 UTC, Hiro527 commented on jp.js
> +item.sell.quick 本当に{0}をクイック販売しますか?
日本語での「セール」はバーゲン(Bargain)の意味になってしまうと思うんですけど、どうでしょうか

2021-04-28 04:34 UTC, mty22 commented on jp.js
> +item.sell.quick 本当に{0}をクイック販売しますか?
raised in pr https://github.com/mty22/krunker.io-translations/pull/161