Some changes in spanish version
mty22/krunker.io-translations pull request #164
Opened 2021-04-29 16:35 UTC by ZenControl

Hello
Im spanish and i wanted to see the spanish version, and i found some errors and some translations, that for me its better what i put, thanks (My krunker name is JeloW-GoKu and my discord is max_halcon#9522)

2021-04-29 17:28 UTC, xlNightmare commented
Hola, hice un review de tus traducciones y he notado que estas cambiando ciertas palabras que tienen otro significado en el codigo, gracias por hacerme saber que una de las lineas no estaba traducida. Hare ciertos edits a tus traducciones y hare otra version de tu edit Gracias. - xlNightmare

2021-04-29 17:30 UTC, xlNightmare requested changes
Going to Edit some of the lines because they are translated in other meaning.

2021-04-29 17:48 UTC, ZenControl commented
de acuerdo, gracias

2021-04-29 17:51 UTC, xlNightmare commented
> de acuerdo
> PD: a lo de poner otros significados en el codigo, soy nuevo en esto, ademas nunca he usado git hub de esta manera, perdon si puse algo que no convenia
> gracias

No te preocupes ya hice la update y todo esta en orden gracias por tu colaboración - xlNightmare

2021-04-29 17:52 UTC, xlNightmare approved these changes
No need for reviewers to check on this one, only corrections and some small tweaks have been made, you can merge @mty22

2021-04-29 17:55 UTC, ZenControl commented
una ultima cosa
tengo que hacer algo para que tus cambios se activen o no es necesario?

2021-04-29 17:57 UTC, xlNightmare commented
> una ultima cosa
> tengo que hacer algo para que tus cambios se activen o no es necesario?

Todo en orden, ya mis cambios fueron hechos solo hay que esperar que la Pull Request sea cerrada por mty (code owner) y los cambios seran hechos.

2021-04-29 17:58 UTC, ZenControl commented
vale, gracias

2021-04-30 14:11 UTC, merged

2021-04-30 14:13 UTC, mty22 commented
KB role sorted, KR queued.