pl.js update (v3.8.6)
mty22/krunker.io-translations pull request #178
Opened 2021-05-11 06:55 UTC by xhg4

Updated based on the 3.8.6 en.js and github's edit history from the previous Polish lang pull request.

There is an important issue with the Polish language in the game - the font used in the game doesn't support certain symboles like ą, ć, ę, ż and so on.

2021-05-11 07:11 UTC, mty22 commented
Just noting from @chonker1337 's work prior: https://github.com/mty22/krunker.io-translations/pull/24#issuecomment-824614605

2021-05-11 08:13 UTC, xhg4 commented
> > There is an important issue with the Polish language in the game - the font used in the game doesn't support certain symboles like ą, ć, ę, ż and so on.
> 
> I also noticed this:
> 
> ![image](https://user-images.githubusercontent.com/2951231/117773730-fff68680-b27b-11eb-80bf-99402abeb7a7.png)
> 
> Are there any alternative characters which we can use?

If I knew the name of the font or if I knew where to find it I could see if there are other characters in that font that could be used here but most likely there aren't such. The part that strikes me as rather odd is that "ó" is actually rendered properly

2021-05-11 08:15 UTC, xhg4 commented
> Just noting from @chonker1337 's work prior: https://github.com/mty22/krunker.io-translations/pull/24#issuecomment-824614605

Yep, mostly taken from this because the translation in that pull request was already reviewed (while those changes were still in place)

2021-05-13 10:07 UTC, mty22 commented
> @mty22 there is an error (not with the translation, but with the ingame display) when it comes to streaks - instead of saying "{0} jest na serii 5 zabójstw" (meaning "{0} is on a 5 kill streak") it says "{0} is jest na serri 5 zabójstw" (meaning "{0} is is on a 5 kill streak"). I've checked the translation file and here it is correct, there seems to be a problem with the game's code when it comes to this

Revert this one back to English. The grammar is hard coded into the game.

> Also, I have a question: in the market one of the names barely even fits the space it's supposed to be in ("Przedmiot broni białej" which translates roughly to "Melee skin"). All other names are translated in a similar way ("Przedmiot...") so we either cut out the "Przedmiot" part from all of them or leave it as it is

Unfortunately, nothing can be done about this at this current stage. :(
 
> Edit2: there is a bug - in the settings there are places where you input links wnd when you swap between the translations, the text in those places doesn't swap immedietaly (it's always 1 lang swap behind, let's say you swap from English to Polish to French, when you swap to French, the text in those places is still displayed in Polish)

Under normal circumstances, you would swap to a specific language and stick with it. Next reload of the game would be OK.

2021-05-13 10:58 UTC, xhg4 commented
Okay, the streak message is reverted to English
Waiting for a reviewer for those small changes

2021-05-23 03:26 UTC, mty22 commented
@xhg4 hey mate - do you know any other native Polish speakers who can review?

2021-05-23 08:30 UTC, xhg4 commented
> @xhg4 hey mate - do you know any other native Polish speakers who can review?

I do, I'll try to find someone willing to review this asap

2021-05-26 13:36 UTC, xhg4 commented
Nevermind, I can't really find anyone willing to review this

2021-05-30 04:28 UTC, mty22 commented
> Nevermind, I can't really find anyone willing to review this

Ah ok, thanks @xhg4  -- ill chase up!

2021-06-04 16:31 UTC, 8-10krunker commented
> Nevermind, I can't really find anyone willing to review this

I could find someone to review this for you guys

2021-06-04 16:31 UTC, 8-10krunker commented
> > Nevermind, I can't really find anyone willing to review this
> 
> Ah ok, thanks @xhg4 -- ill chase up!

I could find someone who is willing to read this

2021-06-05 14:31 UTC, mty22 commented
@8-10krunker go ahead! send them this pull request and let them know i'll compensate with KR!

2021-06-11 17:23 UTC, 8-10krunker commented
> @8-10krunker go ahead! send them this pull request and let them know i'll compensate with KR!

do i send them the link to this page?

2021-06-14 07:35 UTC, mty22 commented
> > @8-10krunker go ahead! send them this pull request and let them know i'll compensate with KR!
> 
> do i send them the link to this page?

Absolutely!!

2021-06-14 16:14 UTC, stdavious requested changes
Hi, I was asked to do a review. The only misspelling I found is:
99. isntancje -> instancje
The rest is correct.

2021-06-14 16:18 UTC, stdavious approved these changes
All correct.

2021-06-14 16:24 UTC, stdavious commented on pl.js
> +player.killstreak {0} on a {1} Kill Streak
"{0} jest na serii {1} zabójstw" is correct

2021-06-14 16:29 UTC, stdavious submitted a review, later dismissed
After reading the messages above, approved. The Polish version is absolutely correct in case you ever want to change back to Polish.

2021-06-14 16:30 UTC, xhg4 commented
> Hi, I was asked to do a review. The only misspelling I found is:
> 99. isntancje -> instancje
> The rest is correct. 

Oops, I'll fix that rn

2021-06-14 16:32 UTC, xhg4 commented
Fixed

@mty22 seems like this is ready to merge

2021-06-28 05:56 UTC, mty22 commented
Looks good! Will merge it through soon! Sorry, been busy IRL with zed's charity event etc.

2021-06-28 19:17 UTC, xhg4 commented
> Looks good! Will merge it through soon! Sorry, been busy IRL with zed's charity event etc.

No problem, take your time

I mean, the translation project doesn't seem to be even remotely close to being important to the game devs sooo

2021-07-06 11:12 UTC, merged