Updates to ru.js based on v3.8.6 en.js (submitted on behalf of chxrge)
mty22/krunker.io-translations pull request #193
Opened 2021-05-23 02:43 UTC by mty22

IGN: https://krunker.io/social.html?p=profile&q=-Chxrge
Discord: `chxrge#1000`

2021-05-23 02:44 UTC, mty22 commented
I've also (politely) asked chxrge to translate:

```
windows.controls.streak0 Streak 1
windows.controls.streak1 Streak 2
windows.controls.streak2 Streak 3
windows.controls.streak3 Streak 4
windows.controls.streak4 Streak 5
windows.controls.premium0 Noclip
windows.controls.premium1 Godmode
windows.controls.premium2 Kill
windows.controls.premium3 Smite
```

2021-05-30 05:10 UTC, mty22 commented
need native speaker to review still~

2021-06-05 15:17 UTC, coeg701 requested changes

2021-06-05 15:17 UTC, coeg701 commented on ru.js
> +settings.client.gameCap Запечатлеть игру
Запечатлеть игру -> Захват игры

2021-06-05 15:17 UTC, coeg701 commented on ru.js
> +settings.client.resetSettings Перезагрузить настройки
Перезагрузить настройки -> Сброс настроек

2021-06-05 15:17 UTC, coeg701 commented on ru.js
> +settings.client.acceleratedCanvas Ускоренный режим
Ускоренный режим -> Аппаратное ускорение Canvas

2021-06-05 15:17 UTC, coeg701 commented on ru.js
>  windows.controls.premium0 Noclip
not really sure what "streak" means here, but overall I think this translation below suits better
Череда -> Серия

2021-06-05 15:17 UTC, coeg701 commented on ru.js
> +windows.controls.premium1 непобедимый
непобедимый -> Режим Бога

2021-06-05 15:17 UTC, coeg701 commented on ru.js
> +server.config.gamRounds Циклы
Циклы -> Раунды

2021-06-05 15:17 UTC, coeg701 commented on ru.js
> +server.config.limitClasses Ограничение персонажей
Ограничение персонажей -> Лимит классов

2021-06-05 15:17 UTC, coeg701 commented on ru.js
> +server.config.tmSize Размер группы
Режим translates as "mode". I think this fits better in russian and it has the same meaning in this context basically
Размер группы -> Режим

2021-06-05 15:17 UTC, coeg701 commented on ru.js
> +settings.quality.flapAnim Анимациа снайперской крышки
Анимациа снайперской крышки -> Анимация снайперской крышки

2021-06-05 15:27 UTC, coeg701 commented
I would also request to update these lines as well: 
settings.reset.confirm Вы уверены, что хотите сбросить ваши настройки?
settings.import Импорт
settings.export Экспорт
settings.experimental.shaderRendering Дублирующий рендеринг

settings.chat.chatBGOp Непрозрачность фона чата

settings.gameplay.challenge Сложный режим

settings.audio.asset Звуки Ассетов
settings.audio.dialogue Звуки Действий

settings.mods.overlay.paste URL Изображения Оверлея Игры

server.config.hitBoxPad Размер хитбоксов

stats.nukes Нюки

2021-06-08 05:50 UTC, Hiro1338 commented on ru.js
> +settings.client.gameCap Запечатлеть игру
Color profile in russia > Цветовой профиль

2021-06-14 12:35 UTC, mty22 commented
I've invited @coeg701 as a collaborator. You're welcome to update this pull request directly by editing the files in the request.

2021-06-28 05:55 UTC, mty22 commented
@coeg701 ? :)

2021-07-18 12:46 UTC, merged