updated it.js
mty22/krunker.io-translations pull request #226
Opened 2021-07-26 21:06 UTC by mxtteismad

updated it.js for version 4.0.9 by mxtteismad (mxtteismad#5209)

2021-07-27 01:56 UTC, mty22 commented
Nice. Thank you!

I've notified @MrGira on Discord to review.

@mxtteismad can you please comment with your Krunker IGN and Discord ID.

2021-07-27 18:49 UTC, MrGira requested changes
@mxtteismad there are some inaccuracies with the translation. 
If you have some doubt's or needs for clarification, don't be afraid to ping me here or on Krunker Bunker's tranlator chat.

2021-07-27 18:49 UTC, MrGira commented on it.js
> +settings.network.hitReg Test della registrazione del colpo
I would suggest the form "Test registrazione dei colpi"

2021-07-27 18:49 UTC, MrGira commented on it.js
> +windows.controls.kickVoteY Vota per kickare [Si]
Change "Si" with "Sì".

2021-07-27 18:49 UTC, MrGira commented on it.js
> +windows.controls.kickVoteY Vota per kickare [Si]
Would be best to translate "Kickare" with "Vota per espellere"

2021-07-27 18:49 UTC, MrGira commented on it.js
> +windows.controls.specFree attiva/disattiva cam libera
Change "Attiva/disattiva" with "Aziona".

2021-07-27 18:49 UTC, MrGira commented on it.js
> +windows.secondary.customOnly Solo custom
Change "custom" with "personalizzate".

2021-07-27 18:49 UTC, MrGira commented on it.js
> +server.config.intermTmr Pausa (s)
The correct translation would be "Intervallo".

2021-07-27 18:49 UTC, MrGira commented on it.js
> +server.config.fallDmgThr Taglio del danno da caduta
"Taglio" is incorrect, the correct form is "Soglia danno da caduta".

2021-07-27 18:49 UTC, MrGira commented on it.js
> +server.config.noDraws Nessun disegno
"Disegno" is incorrect, the "draw" is "pareggio". "Senza pareggi" or "Nessun pareggio" would be best.

2021-07-28 16:58 UTC, MrGira approved these changes
Ok, looks good.
Next time, if you have difficulties understanding the context of a line, feel free to contact me.

2021-07-29 07:13 UTC, merged

2021-07-29 07:15 UTC, mty22 commented
kr queued

thank you