Update zhtr.js (v4.1.4)
mty22/krunker.io-translations pull request #237
Opened 2021-08-04 08:39 UTC by 0v0katai

Major overhaul (Checked and referenced with zh.tr and en.js)

2021-08-08 04:18 UTC, mty22 commented
Very nice! Just need a native speaker to review~

2021-08-12 16:28 UTC, Therealzz requested changes
Done reviewing the file. It's okay overall. Please decide and make changes on the followings for consistency and quality. 

purchase.error.click 點擊</a> 以重試！
app.spectate 點擊開始觀戰
app.play 點擊開始遊戲

settings.interface.hitInd 命中標記
settings.interface.hitColor 命中標記顏色

settings.interface.kd 顯示擊殺死亡比例

settings.interface.speedOffX 移動速度顯示計水平偏移值
settings.interface.speedOffY 移動速度顯示計垂直偏移值

settings.interface.healthNum 名牌

settings.crosshair.dot 中心點

settings.controller.disableCons 停用手柄

settings.viewmodel.fov 視角廣度
settings.viewmodel.fps 武器視角廣度

settings.viewmodel.roundArms 圓滑的手臂

settings.viewmodel.xOff 武器水平偏移值
settings.viewmodel.yOff 武器垂直偏移值
settings.viewmodel.zOff 武器前後偏移值

settings.viewmodel.yOffADS 武器瞄準時的垂直偏移值

settings.editing.scoreOffX 彈出得分水平偏移值
settings.editing.scoreOffY 彈出得分垂直偏移值

settings.editing.progOffX 進度條水準位置偏移值
settings.editing.progOffY 進度條垂直位置偏移值

settings.editing.score.scale 彈出得分大小比例
settings.editing.prog.scale 進度條大小比例
settings.editing.progm.scale 蓄力條大小比例

settings.editing.feedLimit 擊殺訊息列表長度限制

settings.editing.depth 景深圖模式

settings.mods.endmessage 比賽結束後自動訊息

windows.servers.host + 建立遊戲

windows.loadout.stat 擊殺戰績卡
windows.loadout.flag 國家/地區旗幟

windows.mods.drop 將模組文件放在此處或點擊

windows.mods.publish 發佈模組

windows.controls.header 更改控制方式
windows.controls.voice 語音聊天

windows.controls.specObj 目標點視角

windows.controls.reset 重設並返回到起點（僅限速通和跑酷遊戲模式）
windows.host.header 建立自定義遊戲

windows.host.cmaps 社群遊戲
windows.host.modes 選擇遊戲模式

windows.host.preset 創建預先設定檔
windows.host.preset.load 正在載入預先設定檔...
windows.host.preset.name 預先設定名稱

windows.maps.publish 發佈地圖

windows.publish.map.header 發佈或更新地圖

windows.publish.map.update 發佈或更新

windows.store.header 商店

windows.store.market 市集
windows.store.market2 Krunker 市集

windows.mods.community.header 社群模組

error.seek 點擊以搜尋新的遊戲

server.config.maxPlayers 最大玩家數
server.config.minPlayers 最少玩家數

server.config.headshotOnly 僅限爆頭

funds.insufficient 資金餘額不足

account.banned.hack 此帳戶因作弊已被封禁
spin.free.available 立即領取免費 KR ！
windows.host.default.settings 使用地圖預設以允許玩家保存他們的進度及高分
windows.host.rewards 啟用 KR 獎勵將會強制伺服器使用預設設定，並允許玩家從此地圖贏得 KR：

item.view.open 打開模型檢視器
social.profile.sales 出售記錄
social.profile.sales.market 市場出售額

2021-08-13 11:17 UTC, 0v0katai commented
> Done reviewing the file. It's okay overall. Please decide and make changes on the followings for consistency and quality.
> 
> purchase.error.click 點擊 以重試！
> app.spectate 點擊開始觀戰
> app.play 點擊開始遊戲
> 
> settings.interface.hitInd 命中標記
> settings.interface.hitColor 命中標記顏色
> 
> settings.interface.kd 顯示擊殺死亡比例
> 
> settings.interface.speedOffX 移動速度顯示計水平偏移值
> settings.interface.speedOffY 移動速度顯示計垂直偏移值
> 
> settings.interface.healthNum 名牌
> 
> settings.crosshair.dot 中心點
> 
> settings.controller.disableCons 停用手柄
> 
> settings.viewmodel.fov 視角廣度
> settings.viewmodel.fps 武器視角廣度
> 
> settings.viewmodel.roundArms 圓滑的手臂
> 
> settings.viewmodel.xOff 武器水平偏移值
> settings.viewmodel.yOff 武器垂直偏移值
> settings.viewmodel.zOff 武器前後偏移值
> 
> settings.viewmodel.yOffADS 武器瞄準時的垂直偏移值
> 
> settings.editing.scoreOffX 彈出得分水平偏移值
> settings.editing.scoreOffY 彈出得分垂直偏移值
> 
> settings.editing.progOffX 進度條水準位置偏移值
> settings.editing.progOffY 進度條垂直位置偏移值
> 
> settings.editing.score.scale 彈出得分大小比例
> settings.editing.prog.scale 進度條大小比例
> settings.editing.progm.scale 蓄力條大小比例
> 
> settings.editing.feedLimit 擊殺訊息列表長度限制
> 
> settings.editing.depth 景深圖模式
> 
> settings.mods.endmessage 比賽結束後自動訊息
> 
> windows.servers.host + 建立遊戲
> 
> windows.loadout.stat 擊殺戰績卡
> windows.loadout.flag 國家/地區旗幟
> 
> windows.mods.drop 將模組文件放在此處或點擊
> 
> windows.mods.publish 發佈模組
> 
> windows.controls.header 更改控制方式
> windows.controls.voice 語音聊天
> 
> windows.controls.specObj 目標點視角
> 
> windows.controls.reset 重設並返回到起點（僅限速通和跑酷遊戲模式）
> windows.host.header 建立自定義遊戲
> 
> windows.host.cmaps 社群遊戲
> windows.host.modes 選擇遊戲模式
> 
> windows.host.preset 創建預先設定檔
> windows.host.preset.load 正在載入預先設定檔...
> windows.host.preset.name 預先設定名稱
> 
> windows.maps.publish 發佈地圖
> 
> windows.publish.map.header 發佈或更新地圖
> 
> windows.publish.map.update 發佈或更新
> 
> windows.store.header 商店
> 
> windows.store.market 市集
> windows.store.market2 Krunker 市集
> 
> windows.mods.community.header 社群模組
> 
> error.seek 點擊以搜尋新的遊戲
> 
> server.config.maxPlayers 最大玩家數
> server.config.minPlayers 最少玩家數
> 
> server.config.headshotOnly 僅限爆頭
> 
> funds.insufficient 資金餘額不足
> 
> account.banned.hack 此帳戶因作弊已被封禁
> spin.free.available 立即領取免費 KR ！
> windows.host.default.settings 使用地圖預設以允許玩家保存他們的進度及高分
> windows.host.rewards 啟用 KR 獎勵將會強制伺服器使用預設設定，並允許玩家從此地圖贏得 KR：
> 
> item.view.open 打開模型檢視器
> social.profile.sales 出售記錄
> social.profile.sales.market 市場出售額

@Therealzz Adapted most of your suggestions, although some of yours were already existed before you came to review. Nice catch on some really unobvious errors :D

2021-08-22 08:52 UTC, 0v0katai commented
**Summary**
Total of 519 lines changed compared to prior-v4.0.9 version

**Completely translated** - 71 lines
**Clearer translations** - 60+ lines
**Minor changes (terminology, grammar, punctuation, format unification)** - 380+ lines

2021-08-25 03:31 UTC, Awesome-Boy-001 reviewed
Looks good after @Therealzz changed lots of sentences and words. I don't think there are any obvious mistakes, so everything should be looking smoothly in the Traditional Version.

2021-08-28 06:47 UTC, merged

2021-08-28 06:47 UTC, mty22 commented
kr queued