nl.js update v4.2.2
mty22/krunker.io-translations pull request #254
Opened 2021-08-29 08:16 UTC by mty22

Submitted on behalf of nickauthentic

Closes: #219

2021-08-29 08:47 UTC, jodiejomensen requested changes

2021-08-29 08:47 UTC, jodiejomensen commented on nl.js
> +settings.interface.hideNonTrade Verberg Non-Tradable Skins
verberg niet verhandelbare skins

2021-08-29 08:47 UTC, jodiejomensen commented on nl.js
> +settings.crosshairm.type.1 Vorm
shapes = meervoud dus Vormen

2021-08-29 08:47 UTC, jodiejomensen commented on nl.js
> +settings.crosshairm.always Laat Altijd Zien
Laat altijd zien ===> Altijd laten zien, laatste klinkt beter en mooier

2021-08-29 08:47 UTC, jodiejomensen commented on nl.js
> +settings.gameprivacy.rank Ranked Bagde Weergeven
Kleine spellings fout kan gebeuren, "Badge weergeven" moet het zijn

2021-08-29 08:47 UTC, jodiejomensen commented on nl.js
> +windows.store.premium.gift Weet Je Zeker Dat Je'{0}' {1} Dagen Van Premium Cadeur Wilt Doen?
cadeau niet cadeur

2021-08-29 08:55 UTC, nickauthentic approved these changes
Seems good.

2021-08-30 09:21 UTC, mty22 commented
hey @jodiejomensen -- does the latest changes look OK to merge? (submitted on behalf of @nickauthentic)

also please let me know what your Krunker IGN is

2021-08-30 11:58 UTC, jodiejomensen reviewed
> hey @jodiejomensen -- does the latest changes look OK to merge? (submitted on behalf of @nickauthentic)
> 
> also please let me know what your Krunker IGN is


I hope this is the right way to comment, the latest changes do look ok, my krunker ign is FlipBait (https://krunker.io/social.html?p=profile&q=FlipBait)

2021-08-30 23:15 UTC, nickauthentic commented on nl.js
> +windows.store.premium.gift Weet Je Zeker Dat Je'{0}' {1} Dagen Van Premium Cadeu Wilt Doen?
Yeah my bad, changed it now!

2021-09-05 03:03 UTC, merged