Update zhtr.js (v4.2.2)
mty22/krunker.io-translations pull request #258
Opened 2021-08-29 09:03 UTC by 0v0katai

Updated to v4.2.2

2021-08-29 09:33 UTC, mty22 requested changes

2021-08-29 09:33 UTC, mty22 commented on zhtr.js
> +settings.network.netRate 網路傳送率
need to keep `(Hz)`

2021-09-05 18:49 UTC, Awesome-Boy-001 reviewed
Looks great! Sentences and wordings are also very professional and specific.

2021-09-15 21:19 UTC, Awesome-Boy-001 reviewed
Words and sentences are now much better and smooth. Didn't see or catch mistakes.

2021-09-29 19:03 UTC, Awesome-Boy-001 reviewed
Looks good. Didn't find mistakes in the latest commit.

2021-10-03 11:51 UTC, merged