Update it.js
mty22/krunker.io-translations pull request #261
Opened 2021-09-02 19:22 UTC by colpiffero

update version v.4.2.2 by colpiffero#1111

2021-09-02 19:34 UTC, mxtteismad requested changes
i reviewed the changes and those are the ones that i would change:

line 214: Colore barra XP 2
line 255: Immagine del mirino
line 293: Mostra badge premium
line 294: Mostra badge partner
line 295: Mostra badge classificate
line 330: Input Audio/Microfono
line 331: Volume microfono
line 437: Immagine dello sfondo
line 438: URL Immagine dello sfondo

2021-09-03 07:58 UTC, MrGira requested changes
If you have any doubt on the changes I suggested feel free to contact me.

2021-09-03 07:58 UTC, MrGira commented on it.js
> +settings.experimental.optNetwork rete ottimizzata
Capitalize "rete".

2021-09-03 07:58 UTC, MrGira commented on it.js
>  settings.crosshairm.header Crosshair (Throwing)
Translate "Throwing".

2021-09-03 07:58 UTC, MrGira commented on it.js
> +settings.crosshairm.type.1 Forma
Use plural form Forme

2021-09-03 07:58 UTC, MrGira commented on it.js
> +settings.crosshairm.style.1 Cerchio con buco
Translate in "Cerchio vuoto" to be consistent with "Cerchio pieno".

2021-09-03 07:58 UTC, MrGira commented on it.js
> +settings.crosshairm.style.3 Quadrato con buco
Translate in "Quadrato vuoto" to be consistent with "Quadrato pieno".

2021-09-03 07:58 UTC, MrGira commented on it.js
> +settings.crosshairm.always Sempre mostrato
This was translated in "Mostra sempre" during previous translations (line 233), it would be best if kept that way.

2021-09-03 07:58 UTC, MrGira commented on it.js
> +settings.gameprivacy.rank Mostra ranked badge
For lines 293, 294 and 295 move "badge" before the adjective like you did in line 292.
For line 295 ranked could be translated as rango.

2021-09-03 07:58 UTC, MrGira commented on it.js
> +settings.viewmodel.toggleADS Attiva/Disattiva arma in ADS
This refers to the ability of activating the ADS itself so it would be best if translated as "Attiva ADS" or "Attiva mira"/"Attiva zoom mira".

2021-09-03 07:58 UTC, MrGira commented on it.js
> +settings.editing.progmo.color Sovraccarico colore
This refers to the knife throw overcharge so "Colore sovraccarica".

2021-09-03 07:58 UTC, MrGira commented on it.js
> +settings.social.bg.paste URL sfondo immagine
translated to "Immagine di sfondo" or just "Sfondo"

2021-09-03 08:02 UTC, MrGira commented
@mxtteismad 
> 
> 
> i reviewed the changes and those are the ones that i would change:
> 
> line 214: Colore barra XP 2
> line 255: Immagine del mirino
> line 293: Mostra badge premium
> line 294: Mostra badge partner
> line 295: Mostra badge classificate
> line 330: Input Audio/Microfono
> line 331: Volume microfono
> line 437: Immagine dello sfondo
> line 438: URL Immagine dello sfondo

I agree on these translations, although XP was previously translated as ESP so I would leave it that way for consistency.

2021-09-05 03:16 UTC, mty22 commented
Please let me know when this is good to merge. :)

2021-09-05 20:34 UTC, MrGira approved these changes
@mty22 
looks good to me, ready to be merged.

2021-09-15 12:01 UTC, merged

2021-09-15 12:01 UTC, mty22 commented
kr queued