it.js
mty22/krunker.io-translations pull request #291
Opened 2022-01-02 12:57 UTC by rqyz

2022-01-04 01:53 UTC, mty22 commented
Pending review.

2022-01-30 09:34 UTC, mty22 commented
@MrGira are you able to review this one by any chance?

2022-01-30 10:35 UTC, MrGira commented
@mty22 I'm on it

2022-01-30 12:08 UTC, MrGira requested changes
The translations is alright, but there are some changes to be done first.
Please review them carefully.

2022-01-30 12:08 UTC, MrGira commented on it.js
> +social.market.fee Gratis!
Personally I would drop the exclamation mark, but I would say the translation works.

2022-01-30 12:08 UTC, MrGira commented on it.js
> +windows.clan.delete Sei sicuro di voler eliminare definitivamente il clan?
Clans can be re-created so I would leave the first translation.

2022-02-02 12:24 UTC, mty22 commented
Hello @rqyz - can you please re-base and implement suggestions?

2022-02-04 04:38 UTC, mty22 commented
@rqyz I am going to treat this as abandoned as there's been no response for a while and another PR for `it.js` is active.

Feel free to team up with @MrGira

2022-02-04 04:38 UTC, closed without merging