Update nl.js changes 2/2/2022
mty22/krunker.io-translations pull request #310
Opened 2022-02-02 20:11 UTC by nickauthentic

Added some new translations :)

2022-02-02 20:14 UTC, gluzly approved these changes
Perfect!

2022-02-02 20:32 UTC, AdoreMe-GitHub commented on nl.js
> +settings.network.optNet Geoptimaliseerde Netwerken
Correct

2022-02-02 20:33 UTC, AdoreMe-GitHub commented on nl.js
> +settings.experimental.holiday Holiday Effecten
I would change it to "Feestlijke Effecten"

2022-02-02 20:47 UTC, AdoreMe-GitHub requested changes
97. settings.experimental.holiday Holiday Effecten needs to be settings.experimental.holiday Feestlijke effecten

101. settings.experimental.mouseAccel Muis Versnelling needs to be settings.experimental.mouseAccel Muis Acceleratie

221. settings.medals.show Show Medailles needs to be settings.medals.show Weergeef Medailles

548. windows.controls.propRand Selecteer Willekeurig Prop needs to be windows.controls.propRand Selecteer Willekeurige Prop

2022-02-02 20:59 UTC, AdoreMe-GitHub approved these changes
Correctly corrected it 👍

2022-02-03 01:00 UTC, mty22 commented
Hi everyone, thanks for the PR and the efficiency around it.

It's also good to see the original translators back.

Can you all confirm your IGNs, please?

2022-02-03 01:07 UTC, nickauthentic commented
> here you go frzn

https://krunker.io/social.html?p=profile&q=NickAuthentic
https://krunker.io/social.html?p=profile&q=AdoreMe
https://krunker.io/social.html?p=profile&q=Gluzly

2022-02-06 03:20 UTC, merged