Changes for v5.4.4
mty22/krunker.io-translations pull request #356
Opened 2022-02-14 11:58 UTC by Kuriimu

2022-02-14 12:11 UTC, Hiro527 requested changes
とりあえず、現状こうした方が良いんじゃないかなーっていうところだけコメントを付けておきました！他のところは大丈夫だと思います！

自分のリポジトリの方に修正したものをPushすればこっちにも勝手に反映されるので、時間があるときにお願いします🙏急がなくて大丈夫ですよ～

2022-02-14 12:11 UTC, Hiro527 commented on jp.js
> +commands.forfeit.next 最低1ラウンドプレイ
`最低1ラウンドプレイする必要があります`
のが良いかもしれないです。

2022-02-14 12:11 UTC, Hiro527 commented on jp.js
> +commands.forfeit.limit 投票を開始するのは1マッチにつき1度です
`投票を行えるのは1マッチにつき1回までです`
のほうが自然かもしれません
投票は「開始」するより「行う」のほうが合うかと

2022-02-14 12:11 UTC, Hiro527 commented on jp.js
> +commands.forfeit.ended 降参します
`降参しました`
のほうが自然かもです
おそらくこれが表示されるのは降参が決定したあとだと思います

2022-02-14 12:11 UTC, Hiro527 commented on jp.js
> +ranked.join ランクマッチに入りました。 途中で抜けると一時的にバンされます
`ランクマッチに参加しました。マッチ放棄を行うとBANの対象になります`
のほうが良いかもしれません。「BAN」のような言葉は日本語でもそのまま使われることが多いので、そのままでいいと思います。

2022-02-14 12:11 UTC, Hiro527 commented on jp.js
> +event.doubleXP クラスXP二倍有効
`このマッチではクラスXPが2倍になります`
でも良いかもしれません

2022-02-14 12:11 UTC, Hiro527 commented on jp.js
> +ranked.switch マッチ中にクラスは変えられません
`マッチ中にクラスを変更できません`
の方が他の文章とのズレが減るかもしれません。(「～られない」ではなく「～できない/できません」に統一したほうが良いかもしれないです)

2022-02-14 12:11 UTC, Hiro527 commented on jp.js
> +modes.round.switch サイドを変えます。 次のラウンドの準備をしてください
`サイドを交代します。次のラウンドの準備をしてください`
のほうが良いかもしれないです

2022-02-16 09:52 UTC, Hiro527 commented
There are some untranslated sentences.
I'll work for it after this pull request is done.

2022-02-16 10:59 UTC, Hiro527 approved these changes

2022-02-16 11:15 UTC, hassich approved these changes

2022-02-19 08:42 UTC, mty22 commented
Looks good! Missing some translations, although we can sort those out later.

2022-02-19 08:42 UTC, mty22 approved these changes

2022-02-20 07:07 UTC, Hiro527 commented
I'll work for them after this pr is merged

2022-02-23 10:02 UTC, merged