update nl.js v5.4.4
mty22/krunker.io-translations pull request #362
Opened 2022-02-17 10:25 UTC by nickauthentic

Added new translation and changed some older ones. 
Gluzly and AdoreMe helped me with some of them

2022-02-17 10:58 UTC, AdoreMe-GitHub requested changes
927 moet zijn "Kan niet wisselen tijdens de game"

931 moet zijn "Join een team om te spawnen"

937 moet zijn "Je hebt geen prop wissels meer"

938 moet zijn "Je hebt {0} wissels over"

947 tot 950 moet zijn "God Modus"

957 tot 964 moet zijn "Onbeperkte munitie"

970 moet zijn "Wacht tot de wedstrijd begint  om op te geven"

978 moet zijn "werd eruit gegooid"

2022-02-17 11:09 UTC, AdoreMe-GitHub submitted a review, later dismissed
Changed succesfully and looks good 👍😌

2022-02-17 16:11 UTC, gluzly requested changes
97 settings.network.quickplay Forceer Snel Spel
924 ranked.join Joined Ranked Match. Het verlaten van een match resulteert in een tijdelijke verbanning.
everything else is fine. :)

2022-02-17 16:23 UTC, nickauthentic commented
https://krunker.io/social.html?p=profile&q=NickAuthentic
https://krunker.io/social.html?p=profile&q=AdoreMe
https://krunker.io/social.html?p=profile&q=Gluzly

2022-02-17 16:23 UTC, AdoreMe-GitHub submitted a review, later dismissed
Looks good after the changes 👍😌

2022-02-23 10:51 UTC, mty22 commented
champions as usual

2022-02-23 10:52 UTC, merged