Changes to Japanese v5.4.2.
mty22/krunker.io-translations pull request #407
Opened 2022-03-20 14:03 UTC by VoidSequencx

Added changes to v5.4.2(Japanese) #377".
·Changed characters (/ → ／, ? → ？, ! → ！, () → （）, [] →［］)(didn't change every symbol though)
· As seen in the photo from “Japanese: - Player killstreak grammar issue #1”,  the English font and Japanese font seem to be different (English font seems to be more bold), so I changed most of the symbols into 2 byte symbols to make it look cleaner.
· In addition, numbers/English letters seem to be very close to overlapping with the Japanese letters, which are 2 bytes, so I added spaces between numbers/English letters and Japanese letters to avoid overlapping.
· As for line 765, in en.js it was written “server.config.bstOfR Best of”, so I thought it was more appropriate to write “(number) 番勝負” rather than “最大試合数 (number)”. However, as it seems like the number comes right after ”Best of” (For Japanese, it would become 番勝負 (number)), I will keep it as it is.

2022-03-21 02:54 UTC, Hiro527 commented
えっと前回もお話したかもしれないのですが、このPRに含まれている内容がすでにready-to-mergeとなっているPR(#377)と重複しているため、恐らくConflictが生じてしまうと思います。なので、#377のマージ後に一度リベースしていただく必要があると思います。内容のレビューに関しては今できるものはしておきます。よろしくお願いします。

2022-03-21 03:23 UTC, mty22 commented
> · In addition, numbers/English letters seem to be very close to overlapping with the Japanese letters, which are 2 bytes, so I added spaces between numbers/English letters and Japanese letters to avoid overlapping.

This isn't required.

![image](https://user-images.githubusercontent.com/2951231/159201268-46a0f295-1694-418a-9a6d-71001c30b18a.png)

Please revert changes like the example above.

2022-03-21 03:24 UTC, mty22 requested changes

2022-03-21 03:24 UTC, mty22 commented on jp.js
> +settings.dev.extraBan 詳細な BAN 情報
please revert changes like this as it's not required.

2022-03-21 03:28 UTC, Hiro527 requested changes
多くの変更の提案をありがとうございます。ただ、その中で何点か気になる部分があるため、全てではありませんが、一部の箇所にコメントをつけさせて頂きました。
日本語は[CJK](https://www.sophia-it.com/content/CJK)の一つに属するため、基本的には中国語や韓国語と表記の方法を揃えています。文法的な面では一部韓国語を参考にしている部分もあります。
ただ、今回のPRの中ではその整合性を破壊してしまうような変更が含まれています。日本語と同様に、中国語/韓国語もデフォルトのフォントに文字が含まれていないため環境に依存したフォントになってしまいます(リソーススワッパーやMODによる変更は可能ですが)。ですが、カッコを始めとした記号類は2バイト文字を使わずに表記しています。これは、多言語との統一性の維持や、CJK統合漢字に対応したフォントを使用した際に綺麗に表示されるようにするためです。デフォルトでCJK統合漢字やひらがな/カタカナに対応するフォントをCSSファイルで指定しておくべき、という提案は何度かKrunker Bunkerの方でも上がっているため時間の問題ではないのかなと思っています。
また、「...」や英数字の直前/直後に入れるスペースに関しては、読みにくくなってしまう可能性がかなり高いのではないかなと思っています。そのため、個人的にはスペースは無くてよいのではないかなと思っています。

韓国語: [kr.js](https://github.com/mty22/krunker.io-translations/blob/main/kr.js)
簡体字中国語: (zh.js)[https://github.com/mty22/krunker.io-translations/blob/main/zh.js]
繁体字中国語: (zhtr.js)[https://github.com/mty22/krunker.io-translations/blob/main/zhtr).js

2022-03-21 03:28 UTC, Hiro527 commented on jp.js
> +generic.connecting 接続中 ...
文末の「...」に関しては、直前に入るスペースは不要なんじゃないかなと思います。
理由に関してはまとめて後述します

2022-03-21 03:28 UTC, Hiro527 commented on jp.js
> +generic.success 成功！
感嘆符/疑問符も半角のものでいいのではないかなと思います

2022-03-21 03:28 UTC, Hiro527 commented on jp.js
> +app.spectate.controller START を押して観戦する
英単語と日本語の間に入るスペースは体裁が崩れる恐れがあり、読みにくくなる恐れがあると思うのでそのままで良いと思います

2022-03-21 03:28 UTC, Hiro527 commented on jp.js
> +purchase.error.click ここをクリック </a> して、もう一度試してください！
正規表現か何かで置換されたのでしょうか？`</a>`はHTMLのタグなので、実際に表示されるものではありません。
このままでは不自然なスペースが表示されてしまうため、ここのスペースは削除をお願いします。

2022-03-21 03:28 UTC, Hiro527 commented on jp.js
> +purchase.error.limit 1 日の取引限度額を超えている可能性があります
数字の前後のスペースも、英単語と同様に要らないのではないのかなと思います

2022-03-21 03:28 UTC, Hiro527 commented on jp.js
> +settings.network.netRate ネットワークレート（ Hz ）
カッコ類は以前から意図的に2バイト文字の使用を避けていたため、ここで敢えて2バイト文字にする必要は無いのではないかなと思います。

2022-03-21 03:35 UTC, Hiro527 commented
> · As for line 765, in en.js it was written “server.config.bstOfR Best of”, so I thought it was more appropriate to write “(number) 番勝負” rather than “最大試合数 (number)”. However, as it seems like the number comes right after ”Best of” (For Japanese, it would become 番勝負 (number)), I will keep it as it is.

L765は設定項目の名称のため、`最大試合数`という訳し方にしています。なので、このままで大丈夫です。

2022-03-21 04:00 UTC, VoidSequencx commented
Thank you for pointing out the errors. I will close this pull request and fix the issues.

2022-03-21 04:04 UTC, Hiro527 commented
> Thank you for pointing out the errors. I will close this pull request and fix the issues.

閉じずにこのPRのまま進めて問題ないですよ
むしろ別のPRにしてしまうとレビューなども消えるのでこのままやっていただく方がありがたいです

2022-03-21 04:13 UTC, VoidSequencx commented
> > Thank you for pointing out the errors. I will close this pull request and fix the issues.
> 
> 閉じずにこのPRのまま進めて問題ないですよ
> むしろ別のPRにしてしまうとレビューなども消えるのでこのままやっていただく方がありがたいです

わかりました。PRをもう一度開いて訂正します。

2022-03-23 08:34 UTC, Hiro527 commented
Please request review again after merging of #377 and rebasing your repo

2022-03-23 23:44 UTC, VoidSequencx commented
> Please request review again after merging of #377 and rebasing your repo

I understand. I will wait till #377 is merged.

2022-04-04 07:18 UTC, mty22 commented
rebase please

2022-04-13 01:25 UTC, Hiro527 commented
I'll work on this pr to resolve conflicts
It will probably be done today

2022-04-14 10:14 UTC, Hiro527 commented
@VoidSequencx Conflictを解決しておきました
一応内容を確認しておいて下さい。

2022-04-16 07:54 UTC, mty22 commented
@VoidSequencx are you interested still, or are we treating this as abandoned?

2022-04-17 03:35 UTC, Hiro527 commented
Almost changes that he's made on this pr had been ignored and there are only few changes. I feel rest changes are good to take but I think we don't need to merge them absolutely. Depends on frzn but I think if he won't make any responds on this pr, close this one is a way

2022-04-17 07:10 UTC, VoidSequencx commented
@mty22 @Hiro527 I'm sorry I couldn't respond quickly, as I've been busy recently. But yes, I would like to continue with the translation project.

2022-04-21 11:15 UTC, Hiro527 requested changes

2022-04-21 11:15 UTC, Hiro527 commented on jp.js
> +settings.quality.flap スナイパーフラップを表示
「～を表示」とつけてしまうと他の箇所(e.g.マズルフラッシュ)との整合性が取れないため元のままでお願いします

2022-04-21 11:15 UTC, Hiro527 commented on jp.js
> +settings.editing.tracer.offset 曳光弾の座標
これは「曳光弾」というより「弾道」や「弾丸」のほうが自然だと思います

2022-04-21 11:15 UTC, Hiro527 commented on jp.js
> +matchmaker.GameIssue 不明なゲーム参加時の問題
「ゲーム参加時の不明な問題」の方が自然かもしれません

2022-04-21 11:15 UTC, Hiro527 commented on jp.js
> +server.config.slidSpd スライドのスピード
「スライディング」のままで良いと思います

2022-04-21 11:15 UTC, Hiro527 commented on jp.js
> +server.message.arrested {0}がK.P.D.により逮捕されました
[原文](https://github.com/mty22/krunker.io-translations/blob/main/en.js#L981)の表記に合わせるため、「K.P.D」に修正お願いします

2022-04-22 14:40 UTC, VoidSequencx commented on jp.js
> +matchmaker.GameIssue 不明なゲーム参加時の問題
わかりました。変更します。

2022-04-22 14:41 UTC, VoidSequencx commented on jp.js
> +server.config.slidSpd スライドのスピード
わかりました。

2022-04-22 14:42 UTC, VoidSequencx commented on jp.js
> +server.message.arrested {0}がK.P.D.により逮捕されました
わかりました。修正します

2022-04-22 14:58 UTC, VoidSequencx commented on jp.js
> +settings.quality.flap スナイパーフラップを表示
整合性が取れないという点はありますが、[原文](https://github.com/mty22/krunker.io-translations/blob/main/en.js#L151)によると"Muzzle Flash", "**Show** Sniper Flap" と記されているので、その表記に合わせた方が良いのではないでしょうか。

2022-04-22 15:09 UTC, VoidSequencx commented on jp.js
> +settings.editing.tracer.offset 曳光弾の座標
元の「弾丸」に修正します。

2022-04-25 06:00 UTC, Hiro527 commented on jp.js
> +settings.quality.flap スナイパーフラップを表示
原文に合わせるか他の部分に合わせるかになるんですけど、つけようと思えば「〜を表示」ってつけられる部分にも付けていないって言うのと「〜を表示」があると少し長いかな、と感じました
どちらでも問題ないとは思うので、僕も今回は原文に合わせる形でいいと思います

2022-04-25 06:02 UTC, Hiro527 commented
@mty22 sorry for taking a long time
it's ready to merge
i think you'll be busy for days due to moving, please don't rush :)

2022-05-29 06:44 UTC, merged

2022-05-29 06:44 UTC, mty22 commented
kr queued