Small Fixes zh.js
mty22/krunker.io-translations pull request #428
Opened 2022-04-29 15:58 UTC by Kxlici

2022-04-30 06:05 UTC, 0v0katai requested changes

2022-04-30 06:11 UTC, mty22 commented on zh.js
> +settings.network.netRate 网络刷新率 (赫兹）
> @mty22 Should we leave "Hz" in English or can it be translated as 赫兹? (They have the exact same meaning)

@0v0katai / @Kxlici - Please leave 'Hz' in English.

2022-04-30 06:11 UTC, 0v0katai commented
Also, please change line 40 to ”个粉丝“ too (#401)

2022-04-30 06:55 UTC, Kxlici commented on zh.js
> +generic.leave 退出
> The exact meaning of 退出 is quit, while 离开 means "leave".

they actually both means leave and i think that 退出 is more accurate

2022-04-30 06:56 UTC, Kxlici commented on zh.js
> +generic.clan 兵团
公会 more means for club and not clan, i think 兵团 is More accurate

2022-04-30 07:39 UTC, Kxlici commented
please review again, i did some fixes

2022-04-30 08:43 UTC, chewyjm commented on zh.js
> +generic.clan 兵团
公会 will be better translation for clan

2022-04-30 11:03 UTC, 0v0katai requested changes

2022-04-30 16:13 UTC, 0v0katai requested changes

2022-04-30 16:13 UTC, 0v0katai commented on zh.js
> +commands.host {0} 是当前房主。
Since we've used "服务器" in the previous lines "服主" is more appropriate.

2022-04-30 16:33 UTC, Kxlici commented on zh.js
> +commands.host {0} 是当前房主。
then we can change "服务器" to ‘’房间‘’

2022-04-30 16:33 UTC, Kxlici commented on zh.js
> +commands.host {0} 是当前房主。
they basically mean the same thing and "服务器" sounds abit too formal

2022-05-01 10:27 UTC, 0v0katai commented on zh.js
> +generic.clan 兵团
![image](https://user-images.githubusercontent.com/83216408/166141971-973c5b0e-48e7-453d-b698-0ce04ad491a6.png)
![image](https://user-images.githubusercontent.com/83216408/166141977-0c900685-8e5b-474b-a026-675c58179bc5.png)

2022-05-01 11:49 UTC, chewyjm commented on zh.js
> +commands.host {0} 是当前房主。
服主 will be better as we used 'server' in English version.

2022-05-12 00:52 UTC, mty22 commented
@0v0katai can you please ping me when ready to merge. :) thanks

2022-05-21 04:42 UTC, mty22 commented on zh.js
> +commands.host {0} 是当前房主。
Let's stick with `服主`

2022-05-21 07:43 UTC, 0v0katai requested changes

2022-05-21 07:43 UTC, 0v0katai commented on zh.js
> +windows.playerlist.flag 你确定要封禁{0}吗？
Both 标记 and 封禁 are not the clear words to describe 'hackertag'. Now I have 2 proposals on this line:
- 你确定要标记 {0} 为外挂玩家吗？(Are you sure you want to flag {0} as a hacker?)
- 你确定要为 {0} 贴上外挂玩家标签吗？(Are you sure you want to label {0} with hacker tag?)
The first one has some consistency with en.js as it used 'flag', while the second one is a sense-for-sense translation  (as flag = hackertag)

2022-05-21 15:38 UTC, 0v0katai commented on zh.js
> +windows.playerlist.flag 你确定要封禁{0}吗？
![Screenshot_20220521_233728.jpg](https://user-images.githubusercontent.com/83216408/169658823-f30dd700-c759-483c-9b2c-fa5480e8f75b.jpg)

2022-05-22 05:40 UTC, 0v0katai commented on zh.js
> +windows.playerlist.flag 你确定要封禁{0}吗？
Let's go for the first proposal.

2022-05-22 07:53 UTC, 0v0katai approved these changes
@mty22 Ready to merge ;)

2022-05-29 06:35 UTC, mty22 commented
@Kxlici can you please reach out to me with your IGN? (ping me here or discord dm)

2022-05-29 06:39 UTC, merged