Kxlici patch 7
mty22/krunker.io-translations pull request #446
Opened 2022-05-29 12:29 UTC by Kxlici

2022-06-01 03:22 UTC, mty22 commented
There seems to be constant changes to Chinese languages.

@0v0katai can you please let me know why? Is there many ways to describe the same thing?

2022-06-04 04:52 UTC, 0v0katai requested changes
Quite a lot of problems are found, mostly because the suggestions are inaccurate.

2022-06-04 04:52 UTC, 0v0katai commented on zh.js
> +server.config.maxPlayers 最多玩家数
最多 (at most) generally refers to an amount (and not number/value) and also is used for comparison, while 最大 straightforwardly means maximum.

2022-06-04 04:52 UTC, 0v0katai commented on zh.js
> +item.sell.cant.krunker 此物品不能被出售。
item.sell.cant.krunker Item cant be sold **on krunker**.

2022-06-04 09:28 UTC, Kxlici commented on zh.js
> +settings.dev.forceRegen 强制重生玩家
keeping them so they sound the same

2022-06-04 10:39 UTC, Kxlici commented on zh.js
> +server.config.maxPlayers 最多玩家数
最多
![image](https://user-images.githubusercontent.com/104592743/171995580-a5bb47a6-b38b-4e3a-a08c-adca64d7aca9.png)

2022-06-04 10:40 UTC, Kxlici commented on zh.js
> +settings.client.gameCap 游戏录制
for me 游戏录制 sounds more clear and easy to understand

2022-06-04 10:41 UTC, Kxlici commented on zh.js
> +generic.follow 订阅
in china we also use 订阅 sometimes

2022-06-04 10:42 UTC, Kxlici commented on zh.js
> +settings.chat.messages 显示玩家讯息
we do use 讯息

2022-06-04 10:43 UTC, Kxlici commented on zh.js
> +settings.mods.profile 头像
头像 basically means profile picture/image, i've never heard of 头像图片 in china

2022-06-04 10:43 UTC, Kxlici commented on zh.js
> +windows.controls.taunt3 嘲讽（迷因声）
never heard of 模因 in chinese

2022-06-04 10:46 UTC, Kxlici commented on zh.js
> +settings.quality.updRate 限制帧率
limit fps is a noun, fps limit is to Limit the fps so for me 限制帧率 is more accurate

2022-06-04 10:50 UTC, Kxlici commented on zh.js
> +leaderboard.empty 伺服器里没有任何玩家
is clearer for me as it is used for old leaderboard in game, that can show better

2022-06-04 12:02 UTC, SereinP1geon commented on zh.js
> +generic.follow 订阅
> in china we also use 订阅 sometimes

no we don't

2022-06-04 12:04 UTC, SereinP1geon commented on zh.js
> +generic.follow 订阅
> in china we also use 订阅 sometimes

You are carrying out gratuitous duties on him with no solid proof and putting too much unnecessary burden on him. This is too mean bro

2022-06-04 12:40 UTC, SereinP1geon commented on zh.js
> +settings.client.gameCap 游戏录制
> for me 游戏录制 sounds more clear and easy to understand

游戏录制 既可以指录制的游戏文件 又可说是verb，不准确

2022-06-04 12:42 UTC, SereinP1geon commented on zh.js
> +settings.dev.forceRegen 强制重生玩家
> keeping them so they sound the same

强制mean to "yes or no",总是 mean to sometime always...表示频率
not 100% same.
而且保留这样可以让语言多样化，为什么不呢

2022-06-04 12:43 UTC, SereinP1geon commented on zh.js
> +settings.chat.messages 显示玩家讯息
> we do use 讯息

这是简体中文翻译项目啊哥们

2022-06-04 12:45 UTC, SereinP1geon commented on zh.js
> +windows.controls.taunt3 嘲讽（迷因声）
> 



> never heard of 模因 in chinese

Agreement.maybe they are the same

2022-06-04 12:49 UTC, SereinP1geon commented on zh.js
> +settings.quality.updRate 限制帧率
Translate by minecraft:
![E3ZG_2UDYA_6DPX7 JLQDT1](https://user-images.githubusercontent.com/104287277/171999758-f05dde83-dc7e-4b86-a727-9fe2fde7aa24.png)

2022-06-04 12:50 UTC, SereinP1geon commented on zh.js
> +settings.quality.updRate 限制帧率
you see,here are both "upd" and "rate"

2022-06-04 12:52 UTC, SereinP1geon commented on zh.js
> +leaderboard.empty 伺服器里没有任何玩家
> is clearer for me as it is used for old leaderboard in game, that can show better

bro Let's assume this is right, but why use "伺服器" but not "服务器"？

2022-06-04 12:54 UTC, SereinP1geon commented on zh.js
> +server.config.maxPlayers 最多玩家数
> 最多 for me does refers to values, and 最大 kinda refers to quantity
> 
> ![image](https://user-images.githubusercontent.com/104592743/171995580-a5bb47a6-b38b-4e3a-a08c-adca64d7aca9.png)

最大 =>max =>min
最多 =>most => more

2022-06-04 12:58 UTC, SereinP1geon commented on zh.js
> +server.config.maxPlayers 最多玩家数
I think they mean the same thing.

2022-06-04 13:32 UTC, SabiGold commented on zh.js
> +server.config.maxPlayers 最多玩家数
> 最多 for me does refers to values, and 最大 kinda refers to quantity
> 
> ![image](https://user-images.githubusercontent.com/104592743/171995580-a5bb47a6-b38b-4e3a-a08c-adca64d7aca9.png)

I'm a student who major in Chinese Language & Literature, English is not my mother language. The reason why use "最大" is better has two reasons.
1、“最大玩家数” is an abbr for “最大玩家数量”. “数”and“量” usually mean same, but still different. Zheng Xuan's commentary on 《周礼·夏官·量人》 says：“数，多少也；量，长短也。(“数” means “多少”；量 means “长短”)”. This word is a compound word. When we use it, the word that modifies it needs to be restricted by both of the word's roots. So we can only use “最大” that has the widest range of word meanings.
2、“玩家数” is a quantity, quantity uses “大小”；“玩家” is a set, set uses "多少".

2022-06-05 00:33 UTC, 0v0katai commented on zh.js
> +windows.controls.taunt3 嘲讽（迷因声）
Alright, we'll go for 迷因.

2022-06-05 00:41 UTC, 0v0katai commented on zh.js
> +generic.follow 订阅
> in china we also use 订阅 sometimes

B站UP主不会说「订阅我」，反而是「关注我」，订阅是油管用法

2022-06-06 08:26 UTC, 0v0katai commented on zh.js
> +windows.controls.interact 互动
Actually not really. We do use "互动" when we interact with objects in-game, but here it is a keybind setting. In CSGO it is translated as "交互".

2022-06-08 01:45 UTC, 0v0katai commented on zh.js
> +stats.airdrops 召唤空投次数
Alright I'll pass this as other stats also have "数" or "次数".

2022-06-08 15:12 UTC, 0v0katai requested changes

2022-06-08 15:12 UTC, 0v0katai commented on zh.js
> +settings.audio.asset 地图物品音量
Asset here means "game assets" which is a general term for all of the components of a map, including objects, background music, sound effects etc. At this moment "组件" has the closest meaning to "assets".

2022-06-08 15:12 UTC, 0v0katai commented on zh.js
> +settings.social.region 地区数据
数据 means "data" and is quite different from "stats".

2022-06-08 15:12 UTC, 0v0katai commented on zh.js
> +commands.login 登录以使用此指令
I would say Minecraft (zh_cn) translates "command" as 命令. 指令 here is instead used in zhtr.js just like Minecraft (zh_tw).

2022-06-09 02:18 UTC, 0v0katai commented on zh.js
> +settings.local.header 本地化 <span id="requiresRestart"><span style="color: #eb5656">*</span> 需重启游戏</span>
Changed (by myself)

2022-06-09 14:54 UTC, 0v0katai commented on zh.js
> +windows.controls.inspect 考察武器
> can we keep it as 展示武器全貌？

Nope, first 展示武器全貌 is redundant, second you cannot inspect the weapon **fully** and thus cannot say “全貌” (whole appearance), and third CSGO translates it as 检视武器.

2022-06-09 15:40 UTC, 0v0katai requested changes

2022-06-09 15:40 UTC, 0v0katai commented on zh.js
> +ranked.team 请加入一个队伍
“一个”在这里显得有些多余。而且如果加上的话，这带来的隐藏意思是玩家能选择任何一个队伍去加入，但是这在Faceit排位赛中并不适用，因为队伍已经定下来了，他们不能加入其他队伍

2022-06-09 15:40 UTC, 0v0katai commented on zh.js
> +modes.round.win 你的队伍已赢下此轮
轮和回合意思一样，而且上面第927行已经用了“回合”。

2022-06-09 23:42 UTC, 0v0katai approved these changes
@mty22 Good to go

2022-06-10 00:57 UTC, mty22 commented
thanks! can everyone please mention their IGN's here

2022-06-11 10:43 UTC, ItsVenomous commented
ign itsVenomous

2022-06-11 10:52 UTC, 0v0katai commented
0v0katai

2022-06-15 10:54 UTC, 0v0katai approved these changes

2022-07-02 04:06 UTC, merged