small fixes to jp.js
mty22/krunker.io-translations pull request #467
Opened 2022-07-02 07:04 UTC by jinwasused

2022-07-02 07:14 UTC, jinwasused commented
ign : jinshirato

2022-07-02 07:23 UTC, mty22 requested changes

2022-07-02 07:23 UTC, mty22 commented on jp.js
> +settings.interface.dmgType.float
this shouldn't be blank.

both `settings.interface.dmgType.default` and `settings.interface.dmgType.float` are referring to number rounding

eg. rounded up or down for `rounded` (99.8 would become 100 and be displayed), where as a `float` is the exact number with a decimal (99.8 would be displayed)

2022-07-02 07:23 UTC, mty22 commented on jp.js
> +matchmaker.NoMatchingServers ゲームが見つかりませんでした。<br><small>クイックプレイオプションを変更してもう一度試してください。</small>
Try to keep as close as possible to the original translation.

Can you please remove  `。` from both?

2022-07-02 07:23 UTC, mty22 commented on jp.js
>  settings.interface.dmgType Show Damage
「ダメージの表示」どう？

2022-07-02 07:30 UTC, Hiro527 requested changes
いくつかコメントを残したので確認お願いします

2022-07-02 07:30 UTC, Hiro527 commented on jp.js
> +settings.interface.dmgType.float
floatの方が抜けちゃってます

2022-07-02 07:30 UTC, Hiro527 commented on jp.js
> +event.easter.golden.despawn 金色の卵が焼失した
誤字です
焼失->消失

2022-07-02 07:30 UTC, Hiro527 commented on jp.js
> +event.easter.found.old この卵はもう見つけてる！
日本語が少し不自然なので、「この卵は発見済みです！」のような方がいいかもしれません

2022-07-02 07:30 UTC, Hiro527 commented on jp.js
> +event.easter.completed {0} エッグハントを完了した！
こちらも同じく「〜完了しました！」の方がいいかもしれないです

2022-07-02 07:30 UTC, Hiro527 commented on jp.js
> +custom.host.wager 賭けてる間にゲームをホストすることは出来ません。
日本語が少し不自然なので、「賭けに参加している間に〜」の方がいいかもしれません

2022-07-02 07:30 UTC, Hiro527 commented on jp.js
> +server.config.lstChkT タイムを巻き戻して直近のチェックポイント (レース、Bhop)
「〜直近のチェックポイントに戻る」の方がいいかもしれないです

2022-07-02 07:32 UTC, jinwasused commented
了解！

2022-07-02 08:41 UTC, Hiro527 requested changes

2022-07-02 08:41 UTC, Hiro527 commented on jp.js
> +event.easter.golden.despawn 金色の卵が消失した
何度もすいません
他の文と合わせるため「金色の卵が消失**しました**」でお願いします

2022-07-02 08:53 UTC, jinwasused commented on jp.js
> +event.easter.golden.despawn 金色の卵が消失した
ああああああごめん忘れてたぁぁ

2022-07-06 12:17 UTC, Hiro527 approved these changes

2022-07-06 12:18 UTC, Hiro527 commented
大丈夫だと思います～
あと`CONTRIBUTORS.md`に名前を追加したかったらご自由にどうぞ～

2022-07-07 02:33 UTC, Hiro527 commented
`CONTRIBUTORS.md`に追加しておきました

2022-07-07 02:34 UTC, Hiro527 approved these changes

2022-09-18 13:36 UTC, merged

2022-09-18 13:41 UTC, mty22 commented
minor fixes https://github.com/mty22/krunker.io-translations/commit/859ddb75116b0bff28fbf0d4ac859d37fd039549