Update pl.js (v5.7.0)
mty22/krunker.io-translations pull request #480
Opened 2022-07-03 15:25 UTC by ectryliz

I left some of the translation untouched because there are issues with grammar when templating, I also added myself to code owners.

2022-07-14 17:04 UTC, xhg4 requested changes
All issues are addressed in the comments. As usual feel free to change the translation to something that's also different from what I wrote in a comment if you think there's a better translation
Apart from the small issues, this is one of the best translations I've seen while working on pl.js, it's great to be able to collaborate with such a good translator

2022-07-15 00:13 UTC, ectryliz commented on pl.js
> +server.config.nameTags Ukryj nazwy przeciwników
The original translation was changed to only opponents, the github doesn't show that change. https://github.com/mty22/krunker.io-translations/blob/66c9cd44b5074ef7e4917741358ccce5008bedf7/en.js#L753

2022-07-15 00:29 UTC, ectryliz commented on pl.js
>  event.easter.completed {0} completed the Egg hunt!
Still would be strange, "You odnalazł wszystkie jaja!" where it should be "Odnalazłeś wszystkie jaja!"

2022-07-16 09:39 UTC, xhg4 commented on pl.js
>  event.easter.completed {0} completed the Egg hunt!
Oh right, sorry, I completely forgot how it renders if you're the one mentioned in {0}

2022-07-16 09:42 UTC, xhg4 submitted a review, later dismissed
Perfect, ready to merge @mty22

2022-07-16 09:44 UTC, xhg4 commented on pl.js
> +server.config.nameTags Ukryj nazwy przeciwników
Oh, okay, I see

2022-07-26 12:27 UTC, ectryliz commented
@xhg4 I added some small changes to other translations, would appreciate if you could review it again.

2022-07-26 17:28 UTC, xhg4 commented
Okay, I've just checked the commit "update pl.js" and everything looks fine, ready to merge

The commit "merge branch ' mty22:main ' into patch-1"... I guess it's better if @mty22 takes a look at it as:
1. I have no idea what's going on in the majority of the commit
2. That commit should probably be in a separate pull request anyways

2022-07-26 20:27 UTC, ectryliz commented
It's upstream fetch in my own repository, it does absolutely nothing here but github decided to show it (oh well).

2022-07-27 11:33 UTC, xhg4 commented
Ah, I see
Just github being github ig

2022-07-27 11:35 UTC, xhg4 approved these changes

2022-09-18 14:07 UTC, merged