So far my work with Croatian. (plan on finishing of course)
mty22/krunker.io-translations pull request #75
Opened 2021-04-16 14:12 UTC by MilanSCR

This is what I've done so far translating to Croatian. I am working alone, some words simply can't be translated to make sense but I have tried my best so far in most cases.
I plan on doing the whole thing even though I'm really busy with IRL stuff but should be done over the weekend.

Discord: milan#7793 
Krunker IGN: MilanSCR
I am kind of exiled from the community and when it comes to being paid or like any compensation I see why I shouldn't get it ofc, I just wanted to help and this is the best I can do for Krunker.

2021-04-17 11:46 UTC, MilanSCR commented
Translated as much as possible. Will be going back to polish and check for some stupid mistakes but the main thing is pretty much done.

2021-04-17 11:49 UTC, MilanSCR commented
Translated as much as possible. Will be going back to polish and check for some stupid mistakes but the main thing is pretty much done.

2021-04-17 20:08 UTC, MilanSCR commented
Think I did a good job, translated everything possible to make the most sense and work the best.

2021-04-18 11:24 UTC, mty22 commented
@MilanSCR nice!

can you please re-add `en.js` and push another commit ?

https://github.com/mty22/krunker.io-translations/blob/main/en.js

2021-04-18 11:25 UTC, mty22 requested changes

2021-04-18 11:25 UTC, mty22 commented on en.js
> -module.exports = `
need to keep this file, see other comment in PR please

2021-04-18 13:06 UTC, MilanSCR commented
Closing because I'm stupid.
Opening new and actual working one.

2021-04-18 13:06 UTC, closed without merging