Update zh.js
mty22/krunker.io-translations pull request #82
Opened 2021-04-17 18:39 UTC by Awesome-Boy-001

### Major updates/fixes on Chinese, Simplified version of translation, such as pushed in professionalized words & phrases, added in new sentences & words, and fixed some confusing parts.

**Contact:**
Discord ID: Awesome_Boy#7555

2021-04-18 11:11 UTC, mty22 commented
Perfect, thank you.

I'll find a native speaker to review your changes and get back to you on this pull request.

2021-04-19 15:03 UTC, mty22 commented on zh.js
> +module.exports = `
need to remove white space here

2021-04-19 15:07 UTC, mty22 requested changes
Hey there, just need to remove the whitespace on the end of these lines.

Can you fix and push another update please?

2021-04-19 15:07 UTC, mty22 commented on zh.js
> +generic.score 得分
need to remove white space here

2021-04-19 15:07 UTC, mty22 commented on zh.js
> +settings.popup.freeKRPop 显示免费KR弹窗
need to remove white space here

2021-04-19 15:07 UTC, mty22 commented on zh.js
> +settings.dev.extraBan 额外禁令信息
need to remove white space on these lines

2021-04-19 15:07 UTC, mty22 commented on zh.js
> +settings.experimental.mouseFlickFix 鼠标抽动修复
need to remove white space here

2021-04-19 15:07 UTC, mty22 commented on zh.js
> +settings.editing.tracer.offset 示踪轨迹
need to remove white space here

2021-04-19 15:07 UTC, mty22 commented on zh.js
> +settings.mods.borderCol 瞄准镜边界
need to remove white space here

2021-04-19 15:07 UTC, mty22 commented on zh.js
> +funds.out 您目前已用完您的 Krunkies.
need to remove white space on these lines

2021-04-19 15:16 UTC, mty22 commented
@Awesome-Boy-001 need you to check my comment in https://discord.com/channels/448194623580667916/831383180086607922/833722205635739690

this PR is on hold until that is checked.

2021-04-20 14:41 UTC, WpyGG4125 commented
Completed file translation using both files, but idk what to do next

2021-04-21 00:39 UTC, mty22 commented
there's two active PRs: https://github.com/mty22/krunker.io-translations/pull/104/  + this one

2021-04-21 12:47 UTC, mty22 commented
I've made comments in Discord, please have a look:

https://discord.com/channels/448194623580667916/831383180086607922/834227613236461588
https://discord.com/channels/448194623580667916/831383180086607922/834409630837768222

2021-04-25 10:18 UTC, mty22 commented
Hi @Awesome-Boy-001 

I had a chat with ReHou (original Simplified Chinese translator), and asked him to check both pull requests since it became apparent that neither teams would work together.

This is his feedback:

![image](https://user-images.githubusercontent.com/2951231/115989742-2de49580-a603-11eb-8c08-c001f4e0003e.png)

Thank you for the work, although for the sake of the game and the trusted feedback that I've received; I believe in this scenario that it's better we roll with https://github.com/mty22/krunker.io-translations/pull/104

2021-04-25 10:18 UTC, closed without merging