Repatch kr.js
mty22/krunker.io-translations pull request #95
Opened 2021-04-18 16:13 UTC by tr0922

@mty22 @YuniQ152 @apinklover Edited it again, this time with YuniQ!

2021-04-19 09:44 UTC, mty22 commented
Old PR: https://github.com/mty22/krunker.io-translations/pull/63

2021-04-19 09:57 UTC, mty22 commented
@apinklover can you have a quick look at this one please?

2021-04-19 10:31 UTC, zVaderX requested changes
Some of Korean changes.

2021-04-19 10:31 UTC, zVaderX commented on kr.js
> +respawn.auto 자동 리스폰 {0} 후
{0} 후 자동 리스폰 됩니다.

2021-04-19 10:31 UTC, zVaderX commented on kr.js
> +custom.host.ranked 랭크전 준비중 게임 만들기 불가
랭크전 준비중에는 게임 호스트가 불가능 합니다.

2021-04-19 10:31 UTC, zVaderX commented on kr.js
> +account.banned.hack 해킹으로 밴을 당한 계정임.
이 계정은 해킹 또는 불법 프로그램 사용으로 차단되었습니다.

2021-04-19 10:31 UTC, zVaderX commented on kr.js
> +windows.host.default.commands *게임 호스트 명령어는 이 형식에서는 사용할 수 없습니다 /noclip /god /smite 등
/noclip /god /smite 등 게임 호스트 명령어는 이 모드에서 사용할 수 없습니다.

2021-04-19 10:31 UTC, zVaderX commented on kr.js
> +windows.store.wheels.sub 새 스킨을 얻을 기회인 스핀을 통해 당신의 운을 시험해보세요
당신의 운을 이용하여 스핀을 돌리고 새 스킨을 얻어보십시오!

2021-04-19 10:40 UTC, zVaderX commented on kr.js
> +windows.store.wheels.sub 새 스킨을 얻을 기회인 스핀을 통해 당신의 운을 시험해보세요
733

2021-04-19 10:40 UTC, zVaderX commented on kr.js
> +windows.host.default.commands *게임 호스트 명령어는 이 형식에서는 사용할 수 없습니다 /noclip /god /smite 등
731

2021-04-19 10:40 UTC, zVaderX commented on kr.js
> +account.banned.hack 해킹으로 밴을 당한 계정임.
711

2021-04-19 10:40 UTC, zVaderX commented on kr.js
> +custom.host.ranked 랭크전 준비중 게임 만들기 불가
698

2021-04-19 10:40 UTC, zVaderX commented on kr.js
> +respawn.auto 자동 리스폰 {0} 후
697

2021-04-19 23:37 UTC, tr0922 commented
@zVaderX Yeah, I get what you're suggesting, but you should rly ask YuniQ and Apink abt it :/
Also, the line 731 edit was nice, but the 733 edit was kinda not approved when I first suggested it.
YuniQ and Apink said it needs proper formality, so ig we can't rly use that.

2021-04-20 00:47 UTC, zVaderX commented
ok

2021-04-20 01:03 UTC, zVaderX commented on kr.js
> +respawn.auto 자동 리스폰 {0} 후
Edit : {0} 초 후 자동 리스폰 됩니다.

2021-04-20 01:03 UTC, zVaderX commented on kr.js
> +custom.host.ranked 랭크전 준비중 게임 만들기 불가
Edit : 랭크전 준비중에는 게임 호스트가 불가능합니다.

2021-04-20 01:12 UTC, apinklover commented on kr.js
> +respawn.auto 자동 리스폰 {0} 후
I think since the text itself implies an auto respawn, we can shorten it to:
{0}초 후 리스폰됩니다.
This will improve legibility.

2021-04-20 01:15 UTC, zVaderX commented on kr.js
> +respawn.auto 자동 리스폰 {0} 후
Edit2 : {0} 초 후 리스폰됩니다.

2021-04-20 01:16 UTC, apinklover commented on kr.js
> +custom.host.ranked 랭크전 준비중 게임 만들기 불가
Improve legibility by minimizing Hanja and English use:
랭크전 준비 중에는 게임을 만들 수 없습니다.

2021-04-20 01:17 UTC, apinklover commented on kr.js
> +windows.host.default.commands *게임 호스트 명령어는 이 형식에서는 사용할 수 없습니다 /noclip /god /smite 등
Since the sentence is supposed to be additional information, put parentheses around it:
(/noclip, /god, /smite와 같은 호스트 명령어는 비활성화됩니다)

2021-04-20 01:18 UTC, apinklover commented on kr.js
> +windows.store.wheels.sub 새 스킨을 얻을 기회인 스핀을 통해 당신의 운을 시험해보세요
"Test your luck" = "운을 시험하다":
스핀을 돌려서 뽑기 운을 시험해 보세요!

2021-04-20 01:23 UTC, tr0922 commented on kr.js
> +windows.store.wheels.sub 새 스킨을 얻을 기회인 스핀을 통해 당신의 운을 시험해보세요
didn't u tell me that we need formality?

2021-04-20 01:24 UTC, zVaderX commented
- 609 | server.config.slidSpd 슬라이드 속도
+ 609 | server.config.slidSpd 슬라이딩 속도

- 624 | server.config.killRewards 킬 점수
+ 624 | server.config.killRewards 처치 점수

- 697 | respawn.auto 자동 리스폰 {0} 후
+ 697 | respawn.auto {0}초 후 자동 리스폰됩니다.

* 698 | custom.host.ranked 랭크전 준비중 게임 만들기 불가
* 698 | custom.host.ranked 랭크전 준비/진행중에는 게임 호스트가 불가능합니다.

- 700 | funds.out KR이 부족한 것으로 보입니다.
+ 700 | funds.out KR이 부족합니다.

- 708 | settings.loaded 설정 로딩 완료
- 709 | settings.loaded.none 설정 입력 존재하지 않음
+ 708 | settings.loaded 설정을 불러왔습니다.
+ 709 | settings.loaded.none 설정을 찾을 수 없습니다.

- 711 | account.banned.hack 해킹으로 밴을 당한 계정임.
+ 711 | account.banned.hack 이 계정은 핵 프로그램 사용으로 차단되었습니다.
- 712 | account.banned.appeal 밴에 이의제기를 하려면, 여기에 연락을 취하세요.
+ 712 | account.banned.appeal 차단 이의제기를 원하시는 경우 이메일로 연락하십시오.

+ 717 | spin.free.claim 이 스핀은 한 시간마다 한 매치를 끝낸 후에 얻을 수 있습니다.
- 717 | spin.free.claim Free KR 스핀은 한 시간마다 게임을 마치고 받을 수 있습니다.

- 719 | mod.reset.0 리스폰 후 영향을 줌.
- 720 | mod.reset.1 맵 물체는 새로고침의 영향을 받지 않음
+ 719 | mod.reset.0 리스폰 후 적용됩니다.
+ 720 | mod.reset.1 맵 오브젝트는 초기화되지 않습니다.

- 730 | windows.host.default.settings 기본 설정을 허용하면 플레이어의 능력치와 최고점을 보관할 수 있다
+ 730 | windows.host.default.settings 기본 설정을 사용하면 플레이어 진행률과 최고 점수를 저장할 수 있습니다.

- 731 | windows.host.default.commands *게임 호스트 명령어는 이 형식에서는 사용할 수 없습니다 /noclip /god /smite 등
+ 731 | windows.host.default.commands */noclip /god /smite 등의 게임 호스트 명령어는 이 모드에서 사용할 수 없습니다.

* 733 | windows.store.wheels.sub 새 스킨을 얻을 기회인 스핀을 통해 당신의 운을 시험해보세요
* 733 | windows.store.wheels.sub 스핀을 돌려 운을 시험하고 새 스킨을 얻을 기회를 노려보세요.

- 734 | windows.store.currency * 달러 단위는 거래 플랫폼이나 사용 은행에 따라 당신의 지역 통화로 변환될 수 있습니다.
+ 734 | windows.store.currency * 미국 달러(USD)로 표시된 가격은 결제 제공업체나 은행에서 정한 환율에 따라 현지 통화로 환전될 수 있습니다.

- 737 | twitch.link 트위치 계정을 연동하겠습니까?
- 738 | twitch.unlink 트위치 계정의 연동을 해제하시겠습니까?
+ 737 | twitch.link Twitch 계정을 연동하겠습니까?
+ 738 | twitch.unlink Twitch 계정의 연동을 해제하시겠습니까?

More Suggestions (Reviews)

2021-04-20 01:29 UTC, mty22 commented on kr.js
> +windows.store.wheels.sub 새 스킨을 얻을 기회인 스핀을 통해 당신의 운을 시험해보세요
> didn't u tell me that we need formality?

Should really be known without saying it, taking into consideration that your work will be used by thousands of people. :)

2021-04-20 01:33 UTC, zVaderX commented
+ Delete the period on the line 504 because one more period automatically becomes two

2021-04-20 01:46 UTC, zVaderX commented on kr.js
> +account.banned.hack 해킹으로 밴을 당한 계정임.
Edit2 : 해킹 또는 불법 프로그램 사용으로 차단된 계정입니다.

2021-04-20 01:49 UTC, zVaderX commented on kr.js
> +custom.host.ranked 랭크전 준비중 게임 만들기 불가
Edit2 : 랭크전 준비 중에는 게임을 호스트 할 수 없습니다.

2021-04-20 03:35 UTC, tr0922 commented
@zVaderX Does Apink approve of this? If he did then why did he say he needed formality :/
We could've just gone with the smoother one in the first place :D

2021-04-20 03:57 UTC, tr0922 reviewed
@mty22 @YuniQ152 The final Version. Check it! If it's ok then we can use this as the final :)

2021-04-20 03:57 UTC, tr0922 commented on kr.js
> +windows.store.wheels.sub 새 스킨을 얻을 기회인 스핀을 통해 당신의 운을 시험해보세요
@mty22 Yeah, I should rly need some smoothness :D

2021-04-20 10:00 UTC, zVaderX commented
@tr0922 nice bro it became more smooth and natural :)

2021-04-20 11:05 UTC, tr0922 commented
@zVaderX It's all thanks to you man :D I rly didn't notice those probs. It's your good bro XD

2021-04-20 11:50 UTC, mty22 commented
let me know when it's good to merge~

2021-04-20 14:58 UTC, tr0922 commented
@mty22 @zVaderX @YuniQ152 I think we'll go with this version? Maybe merge?

2021-04-21 02:02 UTC, mty22 commented
OK, need to cross check with @apinklover

2021-04-21 02:06 UTC, apinklover commented
@mty22 Approve. After this gets merged, can we work on polishing the existing translations? I have some of them done on my version of kr.js.

2021-04-21 02:08 UTC, apinklover commented
Wait hold up
How about 추방하다 instead of 탈퇴시키다?
It's wayyyy more natural that way

2021-04-21 02:38 UTC, tr0922 commented
@apinklover You're definitely right in the 'smoother' way. Although it's not rly the exact meaning in this situation.
But I think it's far more better, so I'll edit it right now :D

2021-04-21 02:40 UTC, tr0922 commented
@mty22 @zVaderX @YuniQ152 @apinklover The final version. It's complete now, so might as well merge :)
After that, we can polish it like apink suggested. :D

2021-04-21 12:20 UTC, mty22 commented
> @mty22 Approve. After this gets merged, can we work on polishing the existing translations? I have some of them done on my version of kr.js.

no problems!

2021-04-21 12:22 UTC, mty22 commented
@zVaderX @apinklover @tr0922 need you guys to give me a work breakdown in percentages between the three of you -- please post a comment here.

2021-04-21 12:24 UTC, mty22 approved these changes

2021-04-21 12:24 UTC, merged

2021-04-21 13:23 UTC, apinklover commented
How about
@tr0922 65%
@apinklover 20%
@zVaderX 15%

2021-04-21 22:39 UTC, zVaderX commented
@mty22 
@tr0922 55% (changing some of files that apinklover, zVaderX suggested, reviewed korean suggestions, reviewed korean translate)
@apinklover 25% (reviewed korean suggestions, suggested some of)
@zVaderX 20% (reveiewed korean translations, some bug fix)

2021-04-21 23:03 UTC, tr0922 commented
@mty22 @apinklover @zVaderX 
It's your choice guys. Honestly I couldn't have done it all by myself, obviously :)
Thanks so much for the help :D 👍

2021-04-21 23:06 UTC, apinklover commented
@mty22 Ok, how about the middle ground:

@tr0922 60%
@apinklover 20%
@zVaderX 20%

2021-04-21 23:17 UTC, tr0922 commented
@mty22 @apinklover @zVaderX 

> @mty22 Ok, how about the middle ground:
> 
> @tr0922 60%
> @apinklover 20%
> @zVaderX 20%

OK that's poggers :D

2021-04-22 05:35 UTC, zVaderX commented
Nice

2021-04-22 21:47 UTC, apinklover commented
@mty22 Looks like the three of us agreed upon a ratio of 60:20:20 for @tr0922:@zVaderX:@zVaderX.
But what do you need this for? The KR rewards?

2021-04-23 00:02 UTC, tr0922 commented
@apinklover Ppl say it is :/

2021-04-23 00:09 UTC, apinklover commented
@mty22 Fair enough. When can we expect to be compensated?

2021-04-23 01:19 UTC, mty22 commented
> @mty22 Fair enough. When can we expect to be compensated?

When I have time. Been busy IRL with work.

2021-04-23 01:19 UTC, mty22 commented
need IGN's and Discord IDs.

2021-04-23 01:22 UTC, mty22 commented
> need IGN's and Discord IDs.

I see them here: https://github.com/mty22/krunker.io-translations/pull/110/files