Update README.md
mty22/krunker.io-translations pull request #97
Opened 2021-04-18 18:42 UTC by xlNightmare

Adding another reviewer for spanish since he helps me a lot when none of the other two are online and he also has translated some files with me.

2021-04-18 19:11 UTC, Aby3kr commented
Hi, i'm the contributor ^^

2021-04-19 09:21 UTC, mty22 requested changes

2021-04-19 09:21 UTC, mty22 commented on README.md
> +- [Spanish](https://github.com/mty22/krunker.io-translations/blob/main/es.js) (Español) - Translated by [nightz](https://krunker.io/social.html?p=profile&q=xlNightmare) (nightz#6678), reviewed by [MG
`(MGVoltJesk#8000) ,` <-- can you please remove the space between `)` and `,`?

2021-04-19 09:22 UTC, mty22 commented
@Aby3kr also ping me in KB for the role~

2021-04-19 13:46 UTC, mty22 approved these changes

2021-04-19 13:47 UTC, merged

2022-03-27 23:56 UTC, Vanity8685 commented
is their any more grammar issues?